name: berikan
description: Barang bekas menjadi sebuah hal yang dapat menumpuk di sekitar rumah kita setelah membeli barang yang baru. Barang-barang ini jika dibuang akan sayang, tetapi dijual dengan suatu harga pun belum tentu laku. Maka dari itu kami menyediakan sebuah platform di mana orang-orang dapat menghibahkan barang-barang bekas mereka. Jika ada orang yang tertarik untuk mengambil barang bekas tersebut, orang itu dapat melakukan chat kepada penghibah(orang yang memberikan barangnya secara sukarela) untuk melakukan perjanjian kapan dan di mana barang itu akan diambil.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.5
  firebase_auth: ^3.2.0
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.1.0
  intl: ^0.17.0
  google_fonts: ^2.1.0
  http: ^0.13.4
  path_provider: ^2.0.8
  path: ^1.8.0
  image_picker: ^0.8.4+4
  flutter_image_compress: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  fake_cloud_firestore: ^1.2.0
  firebase_auth_mocks: ^0.8.1


flutter:
  uses-material-design: true

  assets:
    - lib/data/assets/profile.png
    - lib/data/assets/profile1.png

